name: Build and Push to Docker Hub
on: push
jobs:
    build-container:
        permissions: write-all
        name: Build Docker container
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Build and Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: maslenkovaso/testdbconnect:latest